#
#    This is a snapcraft build script.
#    Copyright (C) 2022 Jintao Yang <yjt950840@outlook.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#    snapcraft.yaml:
#       snapcraft script.
#       build snap package on Linux.
#

name: sdlpal # you probably want to 'snapcraft register <name>'
version: 'v2.0.1e0ffaf' # just for humans, typically '1.2+git' or '1.3.2'
summary: SDL-based reimplementation of the classic Chinese-language RPG known as PAL. # 79 char long summary
description: |
  SDLPAL is an SDL-based cross-platform reimplementation
  of the classic Chinese RPG game known as PAL.

  **put resources here: ~/snap/sdlpal/current/**
  
  including but not limited to:~/snap/sdlpal/current/*.mkf

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20
license: 'GPL-3.0'

apps:
  sdlpal:
    command: usr/local/bin/launcher.sh
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - audio-playback

parts:
  sdlpal:
    plugin: make
    source: https://github.com/sdlpal/sdlpal.git
    source-type: git
    source-branch: master
    build-packages:
      - gcc
      - make
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libmad0-dev
      - libogg-dev
      - libvorbis-dev
      - libopus-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libmad0
      - libogg0
      - libvorbis0a
      - libopus0
      - libopusfile0
    override-build: |
      cd unix
      make -j $(nproc)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/bin
      cp ./sdlpal ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/

  include-launcher:
    plugin: dump
    source: "https://github.com/Joker2770/sdlpal-snap.git"
    source-depth: 1
    source-branch: main
    source-type: git
    organize:
      "launcher.sh" : usr/local/bin/
    prime:
      - -README*
      - -LICENSE
      - -snap

