#
#    This is a snapcraft build script.
#    Copyright (C) 2022 Jintao Yang <yjt950840@outlook.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#    snapcraft.yaml:
#       snapcraft script.
#       build snap package on Linux.
#

name: sdlpal # you probably want to 'snapcraft register <name>'
version: 'v2.0.9799024' # just for humans, typically '1.2+git' or '1.3.2'
summary: SDL-based reimplementation of the classic Chinese-language RPG known as PAL. # 79 char long summary
description: |
  SDLPAL is an SDL-based cross-platform reimplementation
  of the classic Chinese RPG game known as PAL.

  **Please put resources here: ~/snap/sdlpal/current/**
  
  Necessary resources including but not limited to:
  ~/snap/sdlpal/current/Musics/*.mid
  ~/snap/sdlpal/current/*.mkf
  ~/snap/sdlpal/current/*.dat

# icon: gui/icon.png

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18
license: 'GPL-3.0'
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: ppc64el

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

layout:
  /usr/share/midi/freepats:
    bind: $SNAP/usr/share/midi/freepats
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/timidity:
    bind: $SNAP/etc/timidity
  /etc/fonts:
    bind: $SNAP/etc/fonts

apps:
  sdlpal:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: usr/local/bin/launcher.sh
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    extensions: [gnome-3-28]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - audio-playback
      - gsettings
      - pulseaudio
      - alsa

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  sdlpal:
    after: [alsa-mixin]
    plugin: make
    source: https://github.com/sdlpal/sdlpal.git
    source-type: git
    source-branch: master
    build-packages:
      - gcc
      - make
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libmad0-dev
      - libogg-dev
      - libvorbis-dev
      - libopus-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libmad0
      - libogg0
      - libvorbis0a
      - libopus0
      - libopusfile0
      - libgl1
      - libglvnd0
      - libglx0
      - libpulse0
      - libmodplug1
      - libsndfile1
      - freepats
    override-build: |
      cd unix
      make -j $(nproc)
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/local/bin
      cp ./sdlpal ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/

  include-launcher:
    plugin: dump
    source: "https://github.com/Joker2770/sdlpal-snap.git"
    source-depth: 1
    source-branch: main
    source-type: git
    organize:
      "launcher.sh" : usr/local/bin/
    prime:
      - -README*
      - -LICENSE
      - -snap

